import Foundation

/// Installs/removes the opencode plugin that forwards session lifecycle events
/// to NemoNotch's HookServer. opencode auto-loads `*.ts` from its global
/// `~/.config/opencode/plugin/` directory, so dropping the file IS the
/// registration — no `opencode.json` edit needed. Mirrors HermesHookInstaller.
enum OpencodePluginInstaller {
    private static let pluginDir = NSHomeDirectory() + "/.config/opencode/plugin"
    private static let pluginPath = pluginDir + "/nemonotch-notify.ts"
    static let marker = "nemonotch-opencode-plugin"
    static let version = "v1"

    static var isInstalled: Bool {
        guard let content = try? String(contentsOfFile: pluginPath, encoding: .utf8) else { return false }
        return content.contains(marker)
    }

    static func install() throws {
        try writePlugin()
        LogService.info("opencode plugin installed at \(pluginPath)", category: "OpencodePluginInstaller")
    }

    static func uninstall() throws {
        guard FileManager.default.fileExists(atPath: pluginPath) else { return }
        try FileManager.default.removeItem(atPath: pluginPath)
        LogService.info("opencode plugin uninstalled", category: "OpencodePluginInstaller")
    }

    /// Rewrite the plugin with the current hook-server port. Called on launch /
    /// port change (HookServer) when already installed. No-op otherwise.
    static func refreshScript() throws {
        guard isInstalled else { return }
        try writePlugin()
    }

    private static func writePlugin() throws {
        try FileManager.default.createDirectory(atPath: pluginDir, withIntermediateDirectories: true)
        let port = NotchConstants.hookServerPort
        try pluginSource(port: port).write(toFile: pluginPath, atomically: true, encoding: .utf8)
        LogService.info("Wrote opencode plugin (port \(port))", category: "OpencodePluginInstaller")
    }

    /// Pure generator — the plugin's TS source for a given port. Kept internal
    /// (not private) so it can be unit-tested without touching the filesystem.
    static func pluginSource(port: UInt16) -> String {
        """
        // \(marker) \(version) — auto-generated by NemoNotch. Do not edit by hand.
        // Forwards opencode session lifecycle to NemoNotch for notch notifications.
        const URL_BASE = "http://127.0.0.1:\(port)"

        const post = (body) => {
          try {
            fetch(URL_BASE + "/hook", {
              method: "POST",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify(body),
              signal: AbortSignal.timeout(1500),
            }).catch(() => {})
          } catch (_) {}
        }

        export const NemoNotchNotify = async ({ directory }) => {
          const base = (extra) => ({ cwd: directory, cli_source: "opencode", ...extra })
          return {
            "chat.message": async (input) => {
              const model = input && input.model ? input.model.providerID + "/" + input.model.modelID : undefined
              post(base({ hook_event_name: "UserPromptSubmit", session_id: input.sessionID, model }))
            },
            "tool.execute.before": async (input) => {
              post(base({ hook_event_name: "PreToolUse", session_id: input.sessionID, tool_name: input.tool, tool_use_id: input.callID }))
            },
            "tool.execute.after": async (input) => {
              post(base({ hook_event_name: "PostToolUse", session_id: input.sessionID, tool_name: input.tool, tool_use_id: input.callID }))
            },
            "permission.ask": async (input) => {
              // Notify only — do NOT set output.status; opencode's TUI owns the decision.
              post(base({ hook_event_name: "Notification", session_id: input.sessionID, tool_name: input.type || input.title, tool_use_id: input.id, message: input.title || input.pattern }))
            },
            event: async ({ event }) => {
              const sid = event && event.properties ? event.properties.sessionID : undefined
              if (!sid) return
              if (event.type === "session.idle" || event.type === "session.error") {
                post(base({ hook_event_name: "Stop", session_id: sid }))
              } else if (event.type === "session.compacted") {
                post(base({ hook_event_name: "PreCompact", session_id: sid }))
              }
            },
          }
        }
        """
    }
}
